name: secrets-echo

on:
  workflow_dispatch:
    inputs:
        name:
          description: just a name
          required: true
          default: Paul
       
  pull_request:
      branches: [main]

jobs:
  echo-secret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: EchoPassword
        shell: bash
        run: echo ${{ secrets.password }}